"""Add deleted column to available_buses

Revision ID: 1e0ebcc128ef
Revises: 
Create Date: 2024-10-30 17:30:35.020615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0ebcc128ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
     # Add the 'deleted' column to the 'available_buses' table
    op.add_column('available_buses', sa.Column('deleted', sa.Boolean(), nullable=False, server_default='false'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admin_pkey'),
    sa.UniqueConstraint('email', name='admin_email_key')
    )
    # ### end Alembic commands ###
